return {
    'nvim-treesitter/nvim-treesitter',
    build = ':TSUpdate',
    config = function()
        --require('nvim-treesitter.install').compilers = { 'clang' }

        require('nvim-treesitter.configs').setup({
            -- https://github.com/nvim-treesitter/nvim-treesitter/tree/master?tab=readme-ov-file#supported-languages
            ensure_installed = {
                'bash',
                'c',
                'cpp',
                'css',
                'csv',
                'dhall',
                'diff',
                'dockerfile',
                'dot',
                'git_config',
                'git_rebase',
                'gitattributes',
                'gitcommit',
                'gitignore',
                'graphql',
                'haskell',
                'html',
                'http',
                'ini',
                'java',
                'javascript',
                'jq',
                'jsdoc',
                'json',
                'lua',
                'make',
                'markdown',
                'ninja',
                'nix',
                'passwd',
                'pem',
                'python',
                'rust',
                'scss',
                'smithy',
                'sql',
                'ssh_config',
                'strace',
                'terraform',
                'toml',
                'tsv',
                'typescript',
                'vim',
                'vimdoc',
                'xml',
                'yaml',
            },
            sync_install = false,
            highlight = { enable = true },
            indent = { enable = true },
        })
    end,
}
